services:
  # nginx:
  #   image: nginx:stable-alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - './nginx.conf:/etc/nginx/nginx.conf'
  #   depends_on:
  #     - main-app
  #   networks:
  #     - dev

  main-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: main-app
    ports:
      - "8000:8000"
    command: sh -c "alembic upgrade head && uvicorn --factory app.main:create_app --reload --host 0.0.0.0 --port 8000"
    env_file:
      - ../.env
    depends_on:
      - db
    volumes:
      - ../barber_shop/:/barber_shop/
    networks:
      - backend

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${APP_CONFIG__DB__NAME}
      POSTGRES_USER: ${APP_CONFIG__DB__USER}
      POSTGRES_PASSWORD: ${APP_CONFIG__DB__PASSWORD}
    ports:
      - "5432:5432"
    env_file:
      - ../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge